<a href="https://colab.research.google.com/github/doantronghieu/DEEP-LEARNING/blob/main/CSR_TF_Dev_Pro_Cert/C4/C4_W2_Lab_1_features_and_labels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import tensorflow.keras as tfk
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset = tf.data.Dataset.range(10)

for val in dataset:
    print(val.numpy(), end = ' ')

0 1 2 3 4 5 6 7 8 9 

In [5]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size = 5, shift = 1)

for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy(), end = ' ')
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [6]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size = 5, shift = 1, drop_remainder = True)

for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy(), end = ' ')
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [8]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size = 5, shift = 1, drop_remainder = True)
dataset = dataset.flat_map(lambda window: window.batch(5))

for window in dataset:
    print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [9]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size = 5, shift = 1, drop_remainder = True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))

for x, y in dataset:
    print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [10]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size = 5, shift = 1, drop_remainder = True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size = 10)

for x, y in dataset:
    print(x.numpy(), y.numpy())

[2 3 4 5] [6]
[4 5 6 7] [8]
[0 1 2 3] [4]
[1 2 3 4] [5]
[3 4 5 6] [7]
[5 6 7 8] [9]


In [12]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size = 5, shift = 1, drop_remainder = True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size = 10)
dataset = dataset.batch(2).prefetch(1)

for x, y in dataset:
    print(f'x:\n{x.numpy()}')
    print(f'y:\n{y.numpy()}')
    print()

x:
[[4 5 6 7]
 [1 2 3 4]]
y:
[[8]
 [5]]

x:
[[3 4 5 6]
 [0 1 2 3]]
y:
[[7]
 [4]]

x:
[[2 3 4 5]
 [5 6 7 8]]
y:
[[6]
 [9]]

