<a href="https://colab.research.google.com/github/tronghieu2810/DEEP-LEARNING/blob/main/UDEMY/%5BMike_X_Cohen%5D_Deep_understanding/python/Total_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DATA TYPES

## VARIABLES

In [ ]:
7 + 6

13

In [ ]:
a = 4

In [ ]:
b = 5

In [ ]:
# This code cell inspects the values of the variables
print(a) # Print out a
print(b)

4
5


In [ ]:
c = 7
d = 7.0

type(d)

float

In [ ]:
e = 'Hello'
f = "My name is Harry"

print(f)
print(type(f))

My name is Harry
<class 'str'>


In [ ]:
a_variable_name = 10
filter_order = 18
user_name = 'Harry'
param_4_model_A = 1.234
_3casdf = 4

# not allowed = 123
# 3casdf = 4

In [ ]:
%whos

Variable          Type      Data/Info
-------------------------------------
D                 dict      n=2
E                 dict      n=3
a                 int       4
a_list            list      n=6
a_tuple           tuple     n=6
a_variable_name   int       10
b                 int       5
c                 int       7
d                 float     7.0
e                 str       Hello
f                 str       My name is Harry
filter_order      int       18
first_name        str       My
full_name         str       My name
idx               float     4.0
last_name         str       name
list_list         list      n=9
lst               list      n=6
mix_list          list      n=4
num1              float     11.0
num2              float     2.0
os                module    <module 'os' from 'C:\\Py<...>n\\Python39\\lib\\os.py'>
param_4_model_A   float     1.234
result            bool      True
side_a            float     3.0
side_b            float     4.0
side_c            float  

In [ ]:
# Multiple assignment
var_A = 3
var_B = 'Test'

print(var_A)
print(var_B)

var_A, var_B = 3, 'Test'

3
Test


In [ ]:
var_A = 8
print(type(var_A))

<class 'int'>


## MATH AND PRINTING

In [ ]:
x = 7
y = 4.3
z = 0

In [ ]:
# Floating-point algebra
c = y + 3.5 * x - 7
print(c)

21.8


In [ ]:
print(4 / 3)
c = 4 \
    + 3
print(c)

1.3333333333333333
7


In [ ]:
3 * 2
3 ** 2
9 ** 1/2
9 ** (1/2)

3.0

In [ ]:
first_name = 'My'
last_name  = 'name'

# Overloading
print(first_name + last_name)

full_name = first_name + ' ' + last_name
print(full_name)

# print(first_name - last_name)

print(first_name * 3)
# print(first_name * 3.5)

Myname
My name
MyMyMy


In [ ]:
print('7 * 3 = 2.1')
print(x + y)
# print(x + ' + ' + y + ' = ' + (x + y))
print(str(x) + ' + ' + str(y) + ' = ' + str(x + y))


7 * 3 = 2.1
11.3
7 + 4.3 = 11.3


In [ ]:
# ans = input('Give me a number: ')
# print(ans)
# print(type(ans))

# ans = float(ans)
# print(type(ans))

# ans = float(input('\nGive me a number: '))
# print(ans)
# print(type(ans))

In [ ]:
# Pythagorean theoreom
# c ** 2 = a ** 2 + b ** 2

# Get 02 input from user
#   side 'a'
#   side 'b'
#       Compute and print out the length of side 'c'

# side_a = float(input('Length of side a: '))
# side_b = float(input('Length of side b: '))
# print('')
# side_c = (side_a ** 2 + side_b ** 2) ** (1 / 2)

# print(f'The length of side C is: {side_c}')

## LIST

In [ ]:
a_list = [4, 5, 6, 2, 0, 3]
str_list = ['Hi', 'my', 'name', 'is', 'Harry']
mix_list = [8, 5.01, 'Test', 50.1]
list_list = [1, 2, 3, 'Hi', 'Bye', [0.5, 1/4, 'i'], 4, 5, 6]

print(a_list)
print(type(a_list))
print('')
print(str_list)
print(type(str_list))
print('')
print(mix_list)
print(type(mix_list))
print('')
print(list_list)
print(type(list_list))

[4, 5, 6, 2, 0, 3]
<class 'list'>

['Hi', 'my', 'name', 'is', 'Harry']
<class 'list'>

[8, 5.01, 'Test', 50.1]
<class 'list'>

[1, 2, 3, 'Hi', 'Bye', [0.5, 0.25, 'i'], 4, 5, 6]
<class 'list'>


In [ ]:
list_list = [1, # A number
             2, # This a a parameter
             3, 
             'Hi', # This is the 4th element (index 03)
             'Bye', 
             [0.5, 1/4, 'i'], 
             4, 
             5, 
             6]

In [ ]:
print(a_list)
print(4 in a_list)
print(40 in a_list)
print(40 not in a_list)
print(4 not in a_list)

[4, 5, 6, 2, 0, 3]
True
False
True
False


In [ ]:
print(a_list + str_list)
print(a_list * 3) # Repeat a list
print(str_list * 3)

[4, 5, 6, 2, 0, 3, 'Hi', 'my', 'name', 'is', 'Harry']
[4, 5, 6, 2, 0, 3, 4, 5, 6, 2, 0, 3, 4, 5, 6, 2, 0, 3]
['Hi', 'my', 'name', 'is', 'Harry', 'Hi', 'my', 'name', 'is', 'Harry', 'Hi', 'my', 'name', 'is', 'Harry']


In [ ]:
# Method
print(a_list)
a_list.append(-100)
print(a_list)

[4, 5, 6, 2, 0, 3]
[4, 5, 6, 2, 0, 3, -100]


In [ ]:
print(a_list)
a_list.sort()
print(a_list)

[4, 5, 6, 2, 0, 3, -100]
[-100, 0, 2, 3, 4, 5, 6]


In [ ]:
# Use a list method to find the number of '-100's in list
print(a_list.count(-100))
print(a_list.count(0))
print(a_list.count(100))

1
1
0


In [ ]:
lst = [1, 2, 3, 4, 5]

print(lst)
lst.append(7)
print(lst)

lst.insert(2, 9)
print(lst)

lst.insert(4, 'qwerty')
print(lst)

lst.remove(9)
print(lst)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 7]
[1, 2, 9, 3, 4, 5, 7]
[1, 2, 9, 3, 'qwerty', 4, 5, 7]
[1, 2, 3, 'qwerty', 4, 5, 7]


In [ ]:
# lst.remove(19)
# print(lst)

In [ ]:
# lst.sort()
# print(lst)

In [ ]:
# Remove the string 'qwerty'
lst.remove('qwerty')
print(lst)
# Sort
lst.sort(reverse=True)
print(lst)

[1, 2, 3, 4, 5, 7]
[7, 5, 4, 3, 2, 1]


## TUPLES

In [ ]:
a_tuple = (3, 'abc', 1.2)
print(a_tuple)
print(type(a_tuple))

a_tuple = 3, 'abc', 1.2
print('')
print(a_tuple)
print(type(a_tuple))

print('')
print(a_tuple * 3)

a_list = [3, 'abc', 1.2]

(3, 'abc', 1.2)
<class 'tuple'>

(3, 'abc', 1.2)
<class 'tuple'>

(3, 'abc', 1.2, 3, 'abc', 1.2, 3, 'abc', 1.2)


In [ ]:
# List is mutable
# Tuple is immutable

print(a_list)
print(a_list[0])
a_list[0] = 11
print(a_list)

# print(a_tuple)
# print(a_tuple[0])
# a_tuple[0] = 11
# print(a_tuple)

[3, 'abc', 1.2]
3
[11, 'abc', 1.2]


## BOOLEANS

In [ ]:
t = True
f = False

# True = 234
# t = true, t = TRue

print(type(t))

<class 'bool'>


In [ ]:
print(4 == 4)
print(4 == 4.1)
print(4 == 4.0)

test = (4 == 4)
print(test)

True
False
True
True


In [ ]:
print(4 > 5)
print(44 > 5)
print(7 < 7)
print(7 <= 7)
print(7 != 7)
print(7 != 8)

False
True
False
True
False
True


In [ ]:
# Conjunctive comparison
x = 10
y = 16
print((x > 5) and (x < 15))
# print((x > 5) and ( < 15))
print((x > 5) and (y < 15))
print((x > 5) and (y < 15) and (x + y) < 50)
print((x > 5) and (y > 15) and (x + y) < 50)
print('')
print((x > 5) or (y < 15))
print((x < 5) or (y < 15))

True
False
False
True

True
False


In [ ]:
print(float('5.9'))
print(bool(0))
print(bool(1))
print(bool(10))
print(bool(-10))
print('')
print(bool('true'))
print(bool('false'))
print(bool(''))

5.9
False
True
True
True

True
True
False


In [ ]:
# """
# 1/ Input from the user 3 numbers: a, b, c
# 2/ Check whether c ** 2 = a ** 2 + b ** 2
# 3/ Print out the result
# """

# side_a = float(input('Input length of side a: '))
# side_b = float(input('Input length of side b: '))
# side_c = float(input('Input length of side c: '))

# result = (side_c ** 2 == side_a ** 2 + side_b ** 2)

# print(f'Your answer is: {result}')

## DICTIONARIES

In [ ]:
# Key/Value pairs
D = dict()
print(D)

# [] lists
# () tuples
# {} dict

{}


In [ ]:
# Key       Value
D['name'] = 'Harry'
D['age_range'] = [20, 50]


print(D)

E = {'name': 'Harry', 'age_range': [20, 50], 'Fav_color': 'purple'}

print(E)

{'name': 'Harry', 'age_range': [20, 50]}
{'name': 'Harry', 'age_range': [20, 50], 'Fav_color': 'purple'}


In [ ]:
D['name'] = 'Harrison'

print(D['name'])

Harrison


In [ ]:
print(E.keys())
print('name' in E)
print('Harry' in E)

print('')
print(E.values())

print('')
print(E.items())

dict_keys(['name', 'age_range', 'Fav_color'])
True
False

dict_values(['Harry', [20, 50], 'purple'])

dict_items([('name', 'Harry'), ('age_range', [20, 50]), ('Fav_color', 'purple')])


In [ ]:
# """
# 1/ Input two numbers from the user
# 2/ Create a dict with 03 keys: 'first_num', 'second_num', 'product'
# """

# D = dict()

# num1 = float(input('Number 1: '))
# num2 = float(input('Number 2: '))

# D['first_num'] = num1
# D['second_num'] = num2

# D['product'] = num1 * num2

# print(D.items())

# INDEXING

In [ ]:
a_list = [4, 6, 2, -6, 'qwerty', 10.01]

print(a_list[3])
print(a_list[4])
# print(a_list[4.5])
# print(a_list[4.0])

idx = 4.0
print(a_list[int(idx)])

print('')
print(a_list[len(a_list) - 1])
# print(a_list[len(a_list)])
print(a_list[-1])
print(a_list[-2])

print('')
a_tuple= (4, 6, 2, -6, 'qwerty', 10.01)
print(a_tuple[0])


-6
qwerty
qwerty

10.01
10.01
qwerty

4


In [ ]:
a_list = [4, 6, 2, -6, [10, 20, 30], 10.01]
print(a_list)
print(type(a_list[4]))
print(a_list[4][1])

[4, 6, 2, -6, [10, 20, 30], 10.01]
<class 'list'>
20


# SLICING

In [ ]:
a = range(5, 11)
print(a)
print(type(range(3)))

a = list(range(5, 11))
print(a)
print(a[2])


# a[start:stop:skip]
print('')
print(a[0:2])
print(a[0:3])
print(a[:3])
print(a[1:3])
print(a[3:])

print('')
print(a[::2])
print(a[::3])

print('')
print(a[1::2])
print(a[1::3])
print(a[1::4])
print(a[1::5])

# Reverse a list
print('')
print(a[::-1])

range(5, 11)
<class 'range'>
[5, 6, 7, 8, 9, 10]
7

[5, 6]
[5, 6, 7]
[5, 6, 7]
[6, 7]
[8, 9, 10]

[5, 7, 9]
[5, 8]

[6, 8, 10]
[6, 9]
[6, 10]
[6]

[10, 9, 8, 7, 6, 5]


# FUNCTION

## INPUTS AND OUTPUTS

In [ ]:
print(sum([10, 20, 30]))

var = [1, 2, 3]
print(sum(var))

# var = [1, 2, 3, 'a']
# print(sum(var))

# var = [1, 2, 3, [1, 2, 3]]
# print(sum(var))

var = [1, 2, 3, 1.1]
print(sum(var))

# print(sum[var])

output = sum(var)
print(f'The sum is: {output}')

60
6
7.1
The sum is: 7.1


In [ ]:
# Compute the mean (average) of 'var'
sum(var) / len(var)

1.775

## NUMPY

In [ ]:
import numpy as np

In [ ]:
numbers = [1, 2, 3, 4, 5]

print(np.mean(numbers))

3.0


In [ ]:
x = np.linspace(1, 7, 5)
print(x)
print(type(x))

[1.  2.5 4.  5.5 7. ]
<class 'numpy.ndarray'>


In [ ]:
print(type(numbers))
numbers_np = np.array(numbers)
print(type(numbers_np))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
print(numbers_np.min())

1


In [ ]:
print(type(numbers))
print(np.max(numbers))

<class 'list'>
5


In [ ]:
"""
- in-place operation
- not in-place operation
"""

n = [2, 34, 5, 6, 1, 8, 0, 1, 2, 8, 4]
print(n)

n.sort() # in-place
print(n)

nn = np.array(n)
nn.sort()
print(nn)

[2, 34, 5, 6, 1, 8, 0, 1, 2, 8, 4]
[0, 1, 1, 2, 2, 4, 5, 6, 8, 8, 34]
[ 0  1  1  2  2  4  5  6  8  8 34]


In [ ]:
nnn = [2, 34, 5, 6, 1, 8, 0, 1, 2, 8, 4]
np.sort(nnn) # Not in-place
print(nnn)

nnns = np.sort(nnn)
print(nnns)


[2, 34, 5, 6, 1, 8, 0, 1, 2, 8, 4]
[ 0  1  1  2  2  4  5  6  8  8 34]


## PANDAS

In [ ]:
import pandas as pd

In [ ]:
# Create random data
print(np.random.randn())
print(np.random.randn(5))
print(np.random.randn(5, 5))

0.3370757779896079
[ 1.18464997 -0.57335907 -1.14716552 -1.51954784  0.89152401]
[[-0.01551557  1.95523225  0.67088267 -0.32251679  0.32557383]
 [ 0.90245694  0.35860198  1.79458222  1.88674833 -2.31047704]
 [-0.13055637 -0.06833227  0.66469377  0.61022251  0.11125906]
 [-1.37787576 -0.04099091  0.01314916  1.18378028  0.89544629]
 [-1.21982902  1.99222718 -0.2320755   0.65764897  1.34898459]]


In [ ]:
var1 = np.random.randn(100) * 5 + 20
var2 = np.random.randn(100) > 0
print(var2, '\n')

# Variable labels
labels = ['Temp (C)', 'Ice cream']

# Put them together into a dictionary
D = {labels[0]: var1, labels[1]: var2}
print(D, '\n')

# Import the dictionary into a pandas dataframe
df = pd.DataFrame(data=D)
print(type(df), '\n')

[ True False False False False  True  True False False  True  True False
 False False  True  True  True  True False  True False  True  True  True
  True  True  True  True False False False  True False  True False False
  True  True  True  True  True False  True  True False False False  True
 False False  True  True False  True  True  True False  True  True False
  True  True False False  True False  True  True  True False False False
 False  True  True False False False  True False False False False  True
  True False False  True False False  True False  True False False  True
 False False False  True] 

{'Temp (C)': array([18.88754547, 22.14255828, 20.72231985, 25.89217781, 28.17594797,
       20.82782811, 17.19552264, 19.38713362, 19.37982359, 23.793688  ,
       20.75628574, 19.46027146, 22.04673443,  9.33004075, 17.64377928,
       17.01965656, 18.72721112, 28.57646778, 18.59063799, 23.42339064,
       22.44175081, 12.80006043, 23.86134275, 32.19156873, 13.72817748,
       22.12458

In [ ]:
print(df, '\n')
print(df.head(), '\n')
print(df.count(), '\n')
print(df.mean(), '\n')

     Temp (C)  Ice cream
0   18.887545       True
1   22.142558      False
2   20.722320      False
3   25.892178      False
4   28.175948      False
..        ...        ...
95  25.944358       True
96  14.703421      False
97  25.295752      False
98  12.207251      False
99  18.964218       True

[100 rows x 2 columns] 

    Temp (C)  Ice cream
0  18.887545       True
1  22.142558      False
2  20.722320      False
3  25.892178      False
4  28.175948      False 

Temp (C)     100
Ice cream    100
dtype: int64 

Temp (C)     20.372677
Ice cream     0.500000
dtype: float64 



In [ ]:
# Create a Pandas dataframe with:
#  Integer going from 0 to 10, their square, their log

nums = np.array(range(11))
print(nums, '\n')

df = pd.DataFrame({'nums': nums, 'square': nums ** 2, 'log': np.log(nums)})
print(df)

[ 0  1  2  3  4  5  6  7  8  9 10] 

    nums  square       log
0      0       0      -inf
1      1       1  0.000000
2      2       4  0.693147
3      3       9  1.098612
4      4      16  1.386294
5      5      25  1.609438
6      6      36  1.791759
7      7      49  1.945910
8      8      64  2.079442
9      9      81  2.197225
10    10     100  2.302585


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys


## GETTING HELP ON FUNCTIONS

In [ ]:
x = [1, 2, 3]
print(sum(x))
print(sum(x, 10))

6
16


In [ ]:
# sum?
# help(sum)

Help on built-in function sum in module builtins:

sum(iterable, start=0, /)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [ ]:
# np.linspace??

## CREATING FUNCTIONS

In [ ]:
def awesome_function():
    print(1 + 1)

print('hi')

hi


In [ ]:
awesome_function()

2


In [ ]:
awesome_function

<function __main__.awesome_function>

In [ ]:
def super_awesome_function(input1, input2):
    res = input1 + input2
    return res

In [ ]:
result = super_awesome_function(1, 2)
print(result)

3


In [ ]:
def super_awesome_function(input1, input2):
    prod = input1 * input2
    sum  = input1 + input2
    return (prod, sum)

In [ ]:
result = super_awesome_function(10, -7)
print(result)

prod = result[0]
print(prod)

out1, out2 = super_awesome_function(10, -7)
print(out1, '|', out2)

(-70, 3)
-70
-70 | 3


In [ ]:
# Lambda function
func_name = lambda x : x ** 2 - 1

func_name(4)

15

In [ ]:
"""
Create a function that computes a factorial
4! = 4 * 3 * 2 * 1
Compare against math.factorial()
"""

n = 4
def my_factorial(n):
    return np.prod(np.arange(1, n + 1))

In [ ]:
my_factorial(4)

24

In [ ]:
import math

math.factorial(4)

24

## GLOBAL AND LOCAL VARIABLE SCOPES

In [ ]:
# Local scope
# Global scope

In [1]:
def fun_fun():
    xx = 7
    yy = 10
    print(x)

In [2]:
fun_fun()

7


In [ ]:
# x -> Not define

In [3]:
x = 3
print(x)
print(fun_fun())
print(x)

3
7
None
3


In [4]:
def f2():
    print(z)

In [5]:
z = 13
f2()

13


In [11]:
"""
Write a function that flips a coin N times, and report the average
"""

import numpy as np

def coin_flip(N):
    prop_coin_flips = np.mean(np.random.randn(N) > 0)
    print(f'{N} coin flips had {100 * prop_coin_flips}% heads.')

coin_flip(10)

10 coin flips had 40.0% heads.


## COPIES AND REFERENTS OF VARIABLES

In [1]:
a = [4, 3]
b = a

b[0] = 5
print(a)
print(b)

[5, 3]
[5, 3]


In [2]:
print(id(a))
print(id(b))

2631663155200
2631663155200


In [4]:
c = a[:]
c[0] = 6
print(c)
print(a)
print(id(c))
print(id(a))

[6, 3]
[5, 3]
2631663156864
2631663155200


In [6]:
import copy

a = {'q': 1, 'w': 2}
b = copy.deepcopy(a)

print(id(a))
print(id(b))

2631645203328
2631645202752


## CLASSES AND OBJECT-ORIENTED PROGRAMMING

In [ ]:
# Class: Blueprint for creating a set of attributes and methods
# Instance

In [18]:
class model(object):
    # Constructor method
    def __init__(self, num_layers, num_units, name):
        self.layers  = num_layers # Attributes
        self.units   = num_units
        self.name    = name
        self.weights = 1
    
    def how_many_units(self):
        total_units = self.layers * self.units
        print(f'There are {total_units} in units the model.')
    
    def train_the_model(self, x):
        self.weights += x
        return self.weights
    
    def __str__(self):
        return f'This is a {self.name} architecture.'

In [19]:
m1 = model(12, 5, 'CNN')
m1.how_many_units()

m1.train_the_model(2.5)
str(m1)

There are 60 in units the model.


'This is a CNN architecture.'

In [22]:
"""
Create a new class
1/ Weights should be a random numbers matrix of size (layers * units)
2/ Change the training method to multiply input X and add input Y
"""
import numpy as np

class model2(object):
    # Constructor method
    def __init__(self, num_layers, num_units, name):
        self.layers  = num_layers # Attributes
        self.units   = num_units
        self.name    = name
        self.weights = np.random.randn(num_layers, self.units)
    
    def how_many_units(self):
        total_units = self.layers * self.units
        print(f'There are {total_units} in units the model.')
    
    def train_the_model(self, x, y):
        self.weights += self.weights * x + y
    
    def __str__(self):
        return f'This is a {self.name} architecture.'

In [25]:
m2 = model2(2, 3, 'X')
m2.weights

array([[-0.75548701, -0.18954204,  0.00134429],
       [ 0.56126208, -0.82055356, -0.73683534]])

In [27]:
m2.train_the_model(2, 3)
m2.weights

array([[ 5.20061688, 10.29412161, 12.01209864],
       [17.05135873,  4.61501795,  5.36848193]])

# FLOW CONTROL

## IF-ELSE STATEMENTS

In [4]:
# If statements
# Conditional

x = 4

if True:
    print('This is true!')

if False:
    print('This is true!')

print('Outside if')

if (x == 4):
    print('a')
if 4:
    print('b')
if 0:
    print('c')

This is true!
Outside if
a
b


In [5]:
import numpy as np

In [17]:
r = np.random.randn()

if (r > 0):
    outcome = 'positive'
else:
    outcome = 'negative'

print(f'The number is: {outcome}')

The number is: negative


In [18]:
cake_type = 'carrot'

if (cake_type == 'carrot'):
    print('Total yum!')
elif (cake_type == 'chocolate'):
    print('Yummy as well!')
elif (cake_type == 'fruitcake'):
    print('Is this thing good for me?')
else:
    print("OK, I'll try it!")

Total yum!


In [19]:
cake_type = 'chocolate'

if (cake_type == 'carrot'):
    print('Total yum!')
elif (cake_type == 'chocolate'):
    print('Yummy as well!')
elif (cake_type == 'fruitcake'):
    print('Is this thing good for me?')
else:
    print("OK, I'll try it!")

Yummy as well!


In [20]:
cake_type = 'abc'

if (cake_type == 'carrot'):
    print('Total yum!')
elif (cake_type == 'chocolate'):
    print('Yummy as well!')
elif (cake_type == 'fruitcake'):
    print('Is this thing good for me?')
else:
    print("OK, I'll try it!")

OK, I'll try it!


In [21]:
print('Probably carrot cake.') if (cake_type[0] == 'c') else print('I dunno.')

I dunno.


In [23]:
# Conjunctive conditionals
print((1 < 4) and (4 == 5))

if ((1 < 3) and (4 == 5)):
    print('Both conditionals are true')
else:
    print('At least one conditional is false')

False
At least one conditional is false


In [25]:
"""
Create a function that computes the "dot product" between 02 vectors
    1/ Check both inputs are numpy arrays
    2/ Check the 02 inputs are the same length
    3a/ Break out of the function and give a helpful error message
    3a/ Compute and return the dot product
"""

def dot_product(a, b):
    # Check that both vectors are numpy arrays
    if (not(isinstance(a, np.ndarray) and isinstance(b, np.ndarray))):
        raise Exception('Input must be numpy arrays')
    
    # Check that both vectors have the same length
    if (not(len(a) == (len(b)))):
        raise Exception('Input must be the same length')
    
    # Return the dot product
    return sum(a * b)

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))
print(a * b)
print(dot_product(a, b))

32
[ 4 10 18]


In [28]:
# a = np.array([1, 2])
# b = np.array([4, 5, 6])
# print(dot_product(a, b))

Exception: Input must be the same length

In [29]:
numbers = np.linspace(1, 10, 10)
for i in numbers:
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [33]:
# Modulus
# Parity - odd/even
print(5 / 2)
print(6 % 2)
print(5 % 3)

2.5
0
2


## FOR LOOPS 

In [ ]:
# Embed multiple flow-control statements
for n in range(18):
    if (n % 2 == 0):
        print(f'{n} in an even number')
    else:
        print(f'{n} in an odd number')
    
    print('Done testing.')

0 in an even number
Done testing.
1 in an odd number
Done testing.
2 in an even number
Done testing.
3 in an odd number
Done testing.
4 in an even number
Done testing.
5 in an odd number
Done testing.
6 in an even number
Done testing.
7 in an odd number
Done testing.
8 in an even number
Done testing.
9 in an odd number
Done testing.
10 in an even number
Done testing.
11 in an odd number
Done testing.
12 in an even number
Done testing.
13 in an odd number
Done testing.
14 in an even number
Done testing.
15 in an odd number
Done testing.
16 in an even number
Done testing.
17 in an odd number
Done testing.


In [ ]:
"""
Fibonacci series: [0, 1, 1, 2, 3, 5, 8, 13, 21, ...]
Create a function that reports the Fib. series for input N
"""

def fib_seq(N):
    v = [0, 1]
    for i in range(N - 2):
        v.append(sum(v[-2:]))
    
    print(v)

In [ ]:
fib_seq(7)

[0, 1, 1, 2, 3, 5, 8]


## ENUMERATE AND ZIP

In [41]:
import numpy as np

In [44]:
ns = np.linspace(-5, 5, 7)

for i in range(len(ns)):
    print(f'Index {i} has a value of {ns[i]}')
print('')

for i, n in enumerate(ns):
    # n = ns[i]
    print(f'Index {i} has a value of {n}')

Index 0 has a value of -5.0
Index 1 has a value of -3.333333333333333
Index 2 has a value of -1.6666666666666665
Index 3 has a value of 0.0
Index 4 has a value of 1.666666666666667
Index 5 has a value of 3.333333333333334
Index 6 has a value of 5.0

Index 0 has a value of -5.0
Index 1 has a value of -3.333333333333333
Index 2 has a value of -1.6666666666666665
Index 3 has a value of 0.0
Index 4 has a value of 1.666666666666667
Index 5 has a value of 3.333333333333334
Index 6 has a value of 5.0


In [46]:
text = 'Hello my name is Harry'

vowels = np.zeros(len(text))

for (i, l) in enumerate(text):
    print(i, l)
    
    if (l in 'aeiou'):
        vowels[i] = 1

print(vowels)

0 H
1 e
2 l
3 l
4 o
5  
6 m
7 y
8  
9 n
10 a
11 m
12 e
13  
14 i
15 s
16  
17 H
18 a
19 r
20 r
21 y
[0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0.]


In [47]:
list_A = [3, 4, 5, 6, 3, -17]
list_B = ['q', 'w', 'e', 'r', 't', 'y']

for a, b in zip(list_A, list_B):
    print(f'{a} - {b}')

# for a, b in zip(list_A, list_B):
#     print(f'{a} - {b}')

3 - q
4 - w
5 - e
6 - r
3 - t
-17 - y


In [49]:
list_A = [3, 4, 5, 6]
list_B = ['q', 'w', 'e', 'r', 't', 'y']

for a, b in zip(list_A, list_B):
    print(f'{a} - {b}')

3 - q
4 - w
5 - e
6 - r


In [52]:
"""
Given the following lists, create a dictionary using zip
"""
names  = ['alpha', 'beta', 'gamme']
values = [10, 20, 30]

D = dict(zip(names, values))
print(D)
print(D['alpha'])

{'alpha': 10, 'beta': 20, 'gamme': 30}
10


## CONTINUE

In [53]:
for i in range(10):
    if (i % 2 == 0):
        continue
    
    print(i)

1
3
5
7
9


In [57]:
text = 'HellO, my name is HarrY'

for i in text:
    if (i in 'aeiouAEIOU'):
        continue
    print(i, end='')

Hll, my nm s HrrY

## INITIALIZING VARIABLES

In [58]:
import numpy as np

In [61]:
r = np.zeros(10)
print(type(r))
print(r)

r = np.full(10, 2)
print(type(r))
print(r)

<class 'numpy.ndarray'>
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
[2 2 2 2 2 2 2 2 2 2]


In [62]:
N = 10
r = np.zeros(N)

for i in range(N):
    r[i] = i ** 2
print(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [64]:
N = 10
r = np.array([])

for i in range(N):
    r = np.append(r, i ** 2)
print(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [69]:
"""
Compare three methods of creating an array
- N = 10000
- r[i] = i ** 2
- Time test
"""
import time
N   = 10000
toc = [0] * 3

# List append
tic = time.perf_counter()
r = []

for i in range(N):
    r.append(i ** 2)
toc[0] = 1000 * (time.perf_counter() - tic) # ms

# Numpy append
tic = time.perf_counter()
r = np.array([])

for i in range(N):
    r = np.append(r, i ** 2)
toc[1] = 1000 * (time.perf_counter() - tic) # ms

# Numpy initialization
tic = time.perf_counter()
r = np.zeros(N)
for i in range(N):
    r[i] = i**2
toc[2] = 1000 * (time.perf_counter() - tic) # ms

print(np.round(toc, 2))


[ 3.08 66.11  3.35]


## SINGLE-LINE LOOPS (LIST COMPREHENSION)

In [112]:
import random

print(random.randint(1, 10))

r = random.randint(1, 10)
print('r is large') if (r > 5) else print('r is small')

6


In [113]:
for i in range(10):
    print(i ** 2, end=' ')

0 1 4 9 16 25 36 49 64 81 

In [115]:
[print(i ** 2, end=' ') for i in range(10)]

0 1 4 9 16 25 36 49 64 81 

[None, None, None, None, None, None, None, None, None, None]

In [117]:
lst = [(i ** 2) for i in range(10)]
print(lst)

lst = [(i ** 2) for i in range(10) if (i > 5)]
print(lst)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[36, 49, 64, 81]


In [ ]:
"""
Convert the following loops into single-line loop
"""

In [ ]:
new_list = [''] * 10

# for i in range(10):
#     if (i % 2 == 1):
#         new_list[i] = 'Odd'
#     else:
#         new_list[i] = i

nl = ['Odd' if (i % 2 == 0) else i for i in range(10)]

In [ ]:
# Repeat without using numpy

x1 = np.linspace(-3, 3, 11)
y1 = x1 ** 2

x2 = [i/(5/3) for i in range(-5, 6)]
y2 = [(i ** 2) for i in x2]

## WHILE LOOPS 

In [118]:
toggle = True
i = 0

while toggle:
    print(i, end=' ')
    i += 1
    
    if (i == 8):
        toggle = False

0 1 2 3 4 5 6 7 

In [119]:
i = 0
while True:
    print(i, end=' ')
    i += 1
    if (i == 8): break
    
    # More code -> Don't run :(
        

0 1 2 3 4 5 6 7 

In [120]:
i = 0
while (i < 8):
    print(i, end=' ')
    i += 1

0 1 2 3 4 5 6 7 

In [ ]:
"""
For:   Prefer when you know in advance the number of iterations
While: Prefer when you DON'T know in advance exactly how many iteration
"""

In [121]:
""" Poisson counter
1/ Specify a target number: np.exp(-lambda) | e^lambda, lambda = 10
2/ Initialize a counter = 0, curr_val = 1
3/ Multiply curr_val by a random number U[0, 1]
4/ Repeat step 3 until curr_val < target
5/ Return the number of times that you go through steps 4
"""

import numpy as np

def poisson_counter(lamb):
    # 1/ Specify a target number: np.exp(-lambda) | e^lambda, lambda = 10
    
    # 2/ Initialize a counter = 0, curr_val = 1
    counter, curr_val = 0, 1
    target = np.exp(-lamb)
    
    # 3/ Multiply curr_val by a random number U[0, 1]
    # 4/ Repeat step 3 until curr_val < target
    while (curr_val > target):
        counter  += 1
        curr_val *= np.random.randn()
        
    # 5/ Return the number of times that you go through steps 4
    return counter

In [161]:
poisson_counter(10)

6

## BROADCASTING IN NUMPY

In [165]:
import numpy as np

X = np.array([[1, 2, 3],
            [2, 3, 4],
            [3, 4, 5],
            [4, 5, 6]])

W = np.array([10, 20, 30])

print(X, '\n')
print(W)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]] 

[10 20 30]


In [166]:
Y = np.zeros(X.shape)

for i in range(X.shape[0]):
    Y[i, :] = X[i, :] + W

Y

array([[11., 22., 33.],
       [12., 23., 34.],
       [13., 24., 35.],
       [14., 25., 36.]])

In [168]:
import copy
Y = copy.deepcopy(X)

for i in range(X.shape[0]):
    Y[i, :] = X[i, :] + W

Y

array([[11, 22, 33],
       [12, 23, 34],
       [13, 24, 35],
       [14, 25, 36]])

In [169]:
Z = X + W
Z

array([[11, 22, 33],
       [12, 23, 34],
       [13, 24, 35],
       [14, 25, 36]])

In [172]:
v = np.array([-1, 0, 1, 0])
print(v, '\n')

v = np.array([[-1], [0], [1], [0]])
print(v, '\n')

v = np.array([-1, 0, 1, 0], ndmin=2)
print(v, '\n')

v = np.array([-1, 0, 1, 0], ndmin=2).T
print(v, '\n')

print(X, '\n')
print(X*v)

[-1  0  1  0] 

[[-1]
 [ 0]
 [ 1]
 [ 0]] 

[[-1  0  1  0]] 

[[-1]
 [ 0]
 [ 1]
 [ 0]] 

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]] 

[[-1 -2 -3]
 [ 0  0  0]
 [ 3  4  5]
 [ 0  0  0]]


In [176]:
"""
1/ Create a vector of integers from 0 -> 8 (v)
2/ Reshape v into a 3x3 matrix (M) (np.reshape)
3/ Repeat M into a 9x3 matrix (C) (np.tile)
4/ Broadcast-multiple C with v (B)
"""

v = np.arange(9)
print(v, '\n')

M = np.reshape(v, (3, 3))
print(M, '\n')

C = np.tile(M, (3, 1))
print(C, '\n')

B = C * np.reshape(v, (len(v), 1))
# B = C * np.reshape(v, (-1, 1))
print(B)

[0 1 2 3 4 5 6 7 8] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [ 0  3  6]
 [12 16 20]
 [30 35 40]
 [ 0  6 12]
 [21 28 35]
 [48 56 64]]


## FUNCTION ERROR CHECKING AND HANDLING

# TEXT AND PLOTS

## PRINTING AND STRING INTERPOLATION

## PLOTTING DOTS AND LINES

## SUBPLOT GEOMETRY

## MAKING THE GRAPHS LOOK NICER

## SEABORN

## IMAGES

## EXPORT PLOTS IN LOW AND HIGH RESOLUTION