In [1]:
import numpy as np

In [13]:
A = np.array([
    [56.0, 0.0, 4.4, 68.0],
    [1.2, 104.0, 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]
])
print(A, '\n===========================')

cal = A.sum(axis=0)
print(cal, '\n===========================')

percentage = 100 * A / cal.reshape(1, 4)
print(percentage, '\n===========================')


[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]] 
[ 59.  239.  155.4  76.9] 
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]] 
