In [2]:
import numpy as np

In [12]:
a = np.random.randn(5, 1)
print(a, '\n=====================')
print(a.shape, '\n=====================')
print(a.T, '\n=====================')
print(a.T.shape, '\n=====================')
print(np.dot(a, a.T), '\n=====================')

[[ 0.22634598]
 [ 0.40349508]
 [-0.43096187]
 [ 0.42725214]
 [-1.0950401 ]] 
(5, 1) 
[[ 0.22634598  0.40349508 -0.43096187  0.42725214 -1.0950401 ]] 
(1, 5) 
[[ 0.0512325   0.09132949 -0.09754649  0.0967068  -0.24785792]
 [ 0.09132949  0.16280828 -0.173891    0.17239414 -0.44184329]
 [-0.09754649 -0.173891    0.18572813 -0.18412938  0.47192053]
 [ 0.0967068   0.17239414 -0.18412938  0.18254439 -0.46785822]
 [-0.24785792 -0.44184329  0.47192053 -0.46785822  1.19911283]] 
