In [1]:
# import libraries
import torch
import torch.nn as nn
import torch.nn.functional as F

# Using dropout

In [9]:
# Define a dropout instance and make some data
prob = 0.5

# Create instance of Dropout class
dropout = nn.Dropout(p=prob)

# Vector of ones, 10 elements
x = torch.ones(10)
print(x)

# Let's see what dropout returns
# The values is doubled because 'prob = 0.5'
y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 2., 0., 0., 2., 0., 0., 0., 0., 0.])
tensor(0.4000)


In [11]:
# Dropout is turned off when evaluating the model
# Switch the model into evaluation mode
dropout.eval()

y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [14]:
# Annoyingly, F.dropout() is not deactivated in eval mode:

dropout.eval()
y = F.dropout(x)
print(y)
print(torch.mean(y))

# But you can manually switch it off
y = F.dropout(input=x, training=False)

print('')
print(y)
print(torch.mean(y))

tensor([2., 2., 0., 2., 2., 0., 2., 2., 0., 0.])
tensor(1.2000)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [15]:
# The model needs to be reset after toggling into eval mode
dropout.train() # Apply dropout
y = dropout(x)
print(y) # With dropout

dropout.eval() # Go to test the model
y = dropout(x)
print(y) # Without dropout

# Dropout.train()
y = dropout(x)
print(y) # Without dropout

tensor([2., 0., 0., 2., 0., 2., 2., 2., 2., 2.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
