In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

# Build two models (Objects)

In [2]:
wide_net = nn.Sequential(
    nn.Linear(in_features=2, out_features=4),   # Hidden layer
    nn.Linear(in_features=4, out_features=3)    # Output layer
)

deep_net = nn.Sequential(
    nn.Linear(in_features=2, out_features=2),   # Hidden layer
    nn.Linear(in_features=2, out_features=2),   # Hidden layer
    nn.Linear(in_features=2, out_features=3)    # Output layer
)

# Print them out
print(wide_net)
print('')
print(deep_net)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)

Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


# Peeking inside the network

## Check out the parameters

In [3]:
for p in deep_net.named_parameters():
  print(p)
  print('')

('0.weight', Parameter containing:
tensor([[-0.4294,  0.5764],
        [ 0.2879, -0.3355]], requires_grad=True))

('0.bias', Parameter containing:
tensor([ 0.7003, -0.3052], requires_grad=True))

('1.weight', Parameter containing:
tensor([[-0.0920,  0.5824],
        [-0.3184,  0.0617]], requires_grad=True))

('1.bias', Parameter containing:
tensor([ 0.0281, -0.5521], requires_grad=True))

('2.weight', Parameter containing:
tensor([[ 0.4908, -0.0780],
        [-0.3468, -0.4130],
        [ 0.3071, -0.6803]], requires_grad=True))

('2.bias', Parameter containing:
tensor([-0.3868, -0.2350,  0.0608], requires_grad=True))



## Count the number of nodes ( = the number of biases)

In [4]:
# named_parameters() is an iterable that returns the tuple (name,numbers)
num_nodes_in_wide = 0
for p in wide_net.named_parameters():
  if ('bias' in p[0]):
    num_nodes_in_wide += len(p[1])
print(f'There are {num_nodes_in_wide} nodes in the wide network')

num_nodes_in_deep = 0
for param_name, param_vect in deep_net.named_parameters():
  if ('bias' in param_name):
    num_nodes_in_deep += len(param_vect)
print(f'There are {num_nodes_in_deep} nodes in the deep network')

There are 7 nodes in the wide network
There are 7 nodes in the deep network


## Just the parameters

In [5]:
for p in wide_net.parameters():
  print(p)
  print('')

Parameter containing:
tensor([[-0.2711, -0.6212],
        [-0.5213, -0.2516],
        [ 0.0240,  0.0737],
        [ 0.5318,  0.3161]], requires_grad=True)

Parameter containing:
tensor([-0.5189, -0.0278,  0.0761, -0.4701], requires_grad=True)

Parameter containing:
tensor([[-0.3056, -0.0085,  0.4565, -0.1217],
        [ 0.4355, -0.0502, -0.1551,  0.0265],
        [-0.0359, -0.0742,  0.2659,  0.4071]], requires_grad=True)

Parameter containing:
tensor([ 0.2737, -0.2215, -0.4196], requires_grad=True)



## Now count the total number of trainable parameters

In [6]:
n_params = 0

for p in wide_net.parameters():
  if (p.requires_grad):
    print(f'This piece has {p.numel()} parameters')
    n_params += p.numel()

print(f'-> Total of {n_params} parameters')

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters
-> Total of 27 parameters


## Btw, can also use list comprehension


In [7]:
n_params = np.sum([p.numel() for p in wide_net.parameters() if p.requires_grad])
print(f'Widenet has {n_params} parametes')

n_params = np.sum([p.numel() for p in deep_net.parameters() if p.requires_grad])
print(f'Deepnet has {n_params} parametes')

Widenet has 27 parametes
Deepnet has 21 parametes


In [8]:
# A nice simple way to print out the model info.
from torchsummary import summary
summary(model=wide_net, input_data=(1, 2))


### NOTE ABOUT THE CODE IN THIS CELL:
# torchsummary is being replaced by torchinfo.
# If you are importing these libraries on your own (via pip), then see the following website:
#        https://pypi.org/project/torch-summary/
# However, torchsummary will continue to be supported, so if the code in this cell works (meaning torchsummary is already installed), 
# then you don't need to do anything!

Layer (type:depth-idx)                   Output Shape              Param #
├─Linear: 1-1                            [-1, 1, 4]                12
├─Linear: 1-2                            [-1, 1, 3]                15
Total params: 27
Trainable params: 27
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00


Layer (type:depth-idx)                   Output Shape              Param #
├─Linear: 1-1                            [-1, 1, 4]                12
├─Linear: 1-2                            [-1, 1, 3]                15
Total params: 27
Trainable params: 27
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00