In [1]:
# import libraries
import numpy as np
import torch

In [5]:
# Generate a few random numbers
np.random.randn(5)

array([ 0.10479917, -1.34718418,  0.10035157, -1.15590347,  1.98126582])

In [6]:
# Repeat after fixing the seed (old-but-still-widely-used method)
np.random.seed(17)
print(np.random.randn(5))
print(np.random.randn(5))

# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


# New seed mechanism in numpy

In [14]:
rand_seed_1 = np.random.RandomState(17)
rand_seed_2 = np.random.RandomState(20210530)

print( rand_seed_1.randn(5) ) # same sequence
print( rand_seed_2.randn(5) ) # different from above, but same each time
print( rand_seed_1.randn(5) ) # same as two up
print( rand_seed_2.randn(5) ) # same as two up
print( np.random.randn(5) )   # different every time

# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
# [ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
# [ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
[ 0.0991466   0.63792617  0.70311068 -0.91609315 -0.78601423]


# Now in pytorch

In [15]:
torch.randn(5)

tensor([-1.1172,  0.6344,  1.6241,  0.0429, -2.3194])

In [17]:
torch.manual_seed(17)
print( torch.randn(5) )

# Torch's seed doesn't spread to numpy
print( np.random.randn(5) )

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[ 0.79840199 -0.61007005  1.18540421 -0.71083401 -0.78112893]
