In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create some random matrices
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
C = np.random.randn(3, 7)

# try some multiplications...
print(np.round(a = A@B, decimals = 2)),     print('')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round(a = C.T@A, decimals = 2)),   print('')

[[-1.37 -0.26 -1.2   1.75  0.06]
 [ 1.75  1.69  4.44 -2.7   3.09]
 [-0.3   0.19 -1.17 -0.74  0.4 ]]

[[ 0.49  0.85  1.22  0.3 ]
 [ 1.05  0.19 -1.4   2.06]
 [ 2.77  1.95 -3.53  3.8 ]
 [ 1.92  2.49 -1.55  1.43]
 [ 0.28  1.31  0.78 -0.76]
 [-1.18 -1.09  4.7  -0.95]
 [ 0.76  1.89 -3.35 -0.8 ]]


# Using pytorch

In [10]:
# Create some random matrices
A = torch.randn(3, 4)
B = torch.randn(4, 5)
C1 = np.random.randn(4, 7)
C2 = torch.tensor(data=C1, dtype=torch.float)

# Try some multiplication
print(np.round(a=A@B, decimals=2)),     print('')
# print(np.round(a=A@B.T, decimals=2))
print(np.round(a=A@C1, decimals=2)),    print('')
print(np.round(a=A@C2, decimals=2))

tensor([[-1.0500,  2.3400, -0.3200, -3.0400, -0.8500],
        [ 0.6700, -0.7700, -0.4200,  2.0500,  0.5100],
        [-0.0300,  1.1900,  0.9300, -1.8100, -2.0800]])

tensor([[ 0.2900, -1.2200, -1.7500,  0.2200, -0.2200,  0.0300, -1.6400],
        [ 0.2400,  0.4100,  1.3600, -0.0800, -0.3800, -0.3600,  0.8100],
        [-2.0400,  1.5100, -3.4400, -1.0100,  1.3000,  0.7900,  1.0000]],
       dtype=torch.float64)

tensor([[ 0.2900, -1.2200, -1.7500,  0.2200, -0.2200,  0.0300, -1.6400],
        [ 0.2400,  0.4100,  1.3600, -0.0800, -0.3800, -0.3600,  0.8100],
        [-2.0400,  1.5100, -3.4400, -1.0100,  1.3000,  0.7900,  1.0000]])
