In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [3]:
# Create a vector
v = np.array([1, 40, 2, -3])

# Find and report the maximum and minimum values
min_val = np.min(v)
max_val = np.max(v)
print(f'Min = {min_val}, Max = {max_val}')

# Now for the argmin/max
min_idx = np.argmin(v)
max_idx = np.argmax(v)
print(f'Min index: {min_idx}, Max index: {max_idx}')

# Confirm
print(f'Min value is {v[min_idx]}, Max value is {v[max_idx]}')

Min = -3, Max = 40
Min index: 3, Max index: 1
Min value is -3, Max value is 40


In [6]:
# Repeat with matrix
M = np.array([ [0, 1, 10], 
               [20, 8, 5] ])
print(M), print(' ')

# Various minima in this matrix!
# minimum from ENTIRE matrix
min_val_1 = np.min(M)
print(min_val_1)

# minimum of each column (across rows)
min_val_2 = np.min(M, axis=0)
print(min_val_2)

# minimum of each row (across columns)
min_val_3 = np.min(M, axis=1)
print(min_val_3)

[[ 0  1 10]
 [20  8  5]]
 
0
[0 1 5]
[0 5]


In [8]:
# Various minima in this matrix!
print(M), print('')
# minimum from ENTIRE matrix
min_idx_1 = np.argmin(M)
print(min_idx_1)

# minimum of each column (across rows)
min_idx_2 = np.argmin(M, axis=0)
print(min_idx_2)

# minimum of each row (across columns)
min_idx_3 = np.argmin(M, axis=1)
print(min_idx_3)

[[ 0  1 10]
 [20  8  5]]

0
[0 0 1]
[0 2]


# Now using pytorch

In [9]:
# Create a vector
v = torch.tensor([1, 40, 2, -3])

# Find and report the maximum and minimum values
minval = torch.min(v)
maxval = torch.max(v)

print('Min,max: %g,%g' %(minval,maxval) )


# Now for the argmin/max
minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print('Min,max indices: %g,%g' %(minidx,maxidx) ), print(' ')

# Confirm
print(f'Min val is { v[minidx] }, max val is { v[maxidx] }')

Min,max: -3,40
Min,max indices: 3,1
 
Min val is -3, max val is 40


In [10]:
# Repeat with matrix
M = torch.tensor([ [0,1,10], [20,8,5] ])
print(M), print(' ')

# Various minima in this matrix!
min1 = torch.min(M)        # minimum from ENTIRE matrix
min2 = torch.min(M,axis=0) # minimum of each column (across rows)
min3 = torch.min(M,axis=1) # minimum of each row (across columns)

# Print them out
print(min1), print(' ')
print(min2), print(' ')
print(min2.values)
print(min2.indices)

tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
 
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
 
tensor([0, 1, 5])
tensor([0, 0, 1])


In [12]:
print(type(min2))
print(min2.count)

<class 'torch.return_types.min'>
<built-in method count of torch.return_types.min object at 0x000002371B81EDC0>
